### ISSUE TITLE
$auth->getUser(); error

### ISSUE THREAD

**Issue by bobmolgui** [rafaelwendel/phpsupabase#12]
Hi,
when I try to use the following:

```
try{
    $data = $auth->getUser($bearerToken);
    print_r($data); // show all user data returned
  } catch(Exception $e){
    echo $auth->getError();
}   
```

I receive back an error: 

Client error: `GET
        https://*****.supabase.co/auth/v1/user` resulted in a `401 Unauthorized` response:

"Invalid JWT: unable to parse or verify signature, signature is invalid".

Do you probably know what the problem could be?

**Comment by mblode** [comment]
Hey @bobmolgui, do you remember what the solution was to this issue?

**Comment by rafaelwendel** [comment]
Hi @mblode 

Check your credentials. Was the `$bearerToken` generated correctly?

**Comment by bobmolgui** [comment]
For me, it was the packages. After I updated them, everything worked. What is your error or could you already fix it?
