### ISSUE TITLE
JWT Expired

### ISSUE THREAD

**Issue by manishshahi1** [rafaelwendel/phpsupabase#15]
How to solve the following error:

```
**error: `POST https://xxx.supabase.co/rest/v1/yyy` resulted in a `401 Unauthorized` response:
{"code":"PGRST301","details":null,"hint":null,"message":"JWT expired"}**

```

**Comment by rafaelwendel** [comment]
Hi @manishshahi1 

By default, the JWT is set to expire in 3600 seconds (1 hour). After this downtime, you need to sign in again and generate a new `bearerToken`.

To change the JWT expiry limit, go to `Project Settings` and then `Auth`.
