### ISSUE TITLE
You need to URLencode!

### ISSUE THREAD

**Issue by fred-derf** [rafaelwendel/phpsupabase#22]
diff --git a/vendor/rafaelwendel/phpsupabase/src/QueryBuilder.php b/vendor/rafaelwendel/phpsupabase/src/QueryBuilder.php
index 681afff..32dfd92 100644
--- a/vendor/rafaelwendel/phpsupabase/src/QueryBuilder.php
+++ b/vendor/rafaelwendel/phpsupabase/src/QueryBuilder.php
@@ -113,7 +113,7 @@ class QueryBuilder {
      */
     public function where(string $column, string $value) : QueryBuilder
     {
-        $this->query['where'][] = $column . '=' . $value;
+        $this->query['where'][] = $column . '=' . urlencode($value);
         return $this;
     }

**Comment by mdestafadilah** [comment]
any update, do you create a PR?

**Comment by rafaelwendel** [comment]
hi @fred-derf 

Your contribution was added on version 0.0.7. Thank you very much!!!
