### ISSUE TITLE
Call to undefined method stdClass::update()

### ISSUE THREAD

**Issue by SRLQNL** [rafaelwendel/phpsupabase#26]
public function like_dogs(Request $request){
        $service = new \PHPSupabase\Service(
            "eyJhbGciwOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAicW3VwYWJhc2UiLAogICJApYXQiOiAxNjkxNzkxMjAwLAogICJleHAiOiAxODQ5NjQ0MDAwCn01.l9f3OhYMcvuuf14WKbF6zdSoNfP3TXz7yViMkNIgV0w", 
            "https://viz6101212.ru"
        );
        $db = $service->initializeDatabase('Posts', 'id');
        $postId = $request->input('postId');
        $post_sent = $db->findBy('id', $postId)->getResult();
        $post_sent = $post_sent["0"];
        $liked_ids = $post_sent->likedIDs;
        $disliked_ids = $post_sent->dislikedIDs;
        if (in_array(\Session::get('uid'), $disliked_ids)) {
            $post_sent->update([

            ]);
            $post_sent->update([
                
            ]);
            return redirect()->back();
        }
        if (in_array(\Session::get('uid'), $liked_ids)) {
            $post_sent->update([
                
            ]);
            return redirect()->back();
        }
        else{
            $post_sent->update('likedIDs',\Session::get('uid'));
            return redirect()->back();
        }
    }

**Comment by rafaelwendel** [comment]
Hi @SRLQNL, 

The object returned by `$db->findBy` is a php standard class. It does not have the `update` method.

Instead of using `$post_sent->update`, use `$db->update`.

Best regards
