### ISSUE TITLE
signInWithRefreshToken doesn't work.

### ISSUE THREAD

**Issue by ubudee** [rafaelwendel/phpsupabase#28]
edit: i made sure the refresh token is not used anywhere else and this also happens with new refresh tokens created one second before running this code and receiving the error.

I have signed in before this codes runs and saved the session in my cookies.
After 1 hour it runs the following code.
Result is either null or this:

![image](https://github.com/rafaelwendel/phpsupabase/assets/78762745/d3a553de-b297-4848-a8ec-53d4bcfdede7)

This is the code for refreshing:

![image](https://github.com/rafaelwendel/phpsupabase/assets/78762745/c397b237-e173-4a8c-971e-5dedb95737e6)

**Comment by ubudee** [comment]
Turned out to be my own mistake.

**Comment by Soben** [comment]
> Turned out to be my own mistake.

What was the mistake?
