### ISSUE TITLE
Remove user

### ISSUE THREAD

**Issue by PoeHaH** [rafaelwendel/phpsupabase#3]
There is a `getUser` function, but no `removeUser` function. 

I tried adding it myself by looking at their JS SDK but don't find the correct REST endpoint (tried `/admin/user/[id]` but that doesn't seem to work for me). 

Any chance you can add it in?

**Comment by rafaelwendel** [comment]
Hello PoeHaH,

For now the function to remove users is not available in the PHPSupaBase library. This functionality requires the use of the project's "service_role" key, which makes the process insecure.

Anyway, I read the official documentation and couldn't find the endpoint and parameters needed to implement this functionality.

Sorry for not being able to help you.

**Comment by PoeHaH** [comment]
No problem, thanks for your help!

**Comment by rafaelwendel** [comment]
Closing...
