### ISSUE TITLE
captcha verification process failed

### ISSUE THREAD

**Issue by yunsimple** [rafaelwendel/phpsupabase#30]
When I enable "Bot and Abuse Protection" using the service_role key it says "Server error: `POST https://sdqczznijvha.supabase.co/auth/v1/signup` resulted in a `500 Internal Server Error` response : {"code":500,"msg":"captcha verification process failed","error_id":"8611cf16c0276459-SJC"} "

When I also use this service_role key from javascript I am able to skip verification.

I'm using version 0.0.7.

**Comment by rafaelwendel** [comment]
Hi @yunsimple 

When you enable  Bot and Abuse Protection, you need to add Authorization (`$service->setBearerToken("YOUR_KEY")`).

=)

**Comment by yunsimple** [comment]
Thanks for the feedback, I'll go in and try it.
