### ISSUE TITLE
Sort Order

### ISSUE THREAD

**Issue by sharkstate** [rafaelwendel/phpsupabase#4]
Ive used the QueryBuilder to order the results like so:

```
    $listProducts = $query->select('*')
                ->from('table')
                ->range('0-0')
                ->order('color')
                ->execute()
                ->getResult();
```

Which gives me the first result ordering by 'color' descending. How can I do the same thing but ascending?

Thanks!

**Comment by rafaelwendel** [comment]
Hello sharkstate,

By default, the "order" method shows the data in ascending order. Anyway, you can make your ordering explicit.
```php
    $listProducts = $query->select('*')
                ->from('table')
                ->range('0-0')
                ->order('color.asc') //or "color.desc"
                ->execute()
                ->getResult();
```
Hope this helps!
